# fne/constants.py
STATUS_QUEUED = "QUEUED"
STATUS_CERTIFIED = "CERTIFIED"
STATUS_PDF_PENDING = "PDF_PENDING"
STATUS_PDF_READY = "PDF_READY"
STATUS_PDF_FAILED = "PDF_FAILED"
STATUS_FAILED = "FAILED"
STATUS_DEAD = "DEAD"
STATUS_DISABLED = "DISABLED"

FNE_INVOICE_TYPE_SALE = "sale"
FNE_INVOICE_TYPE_PURCHASE = "purchase"
FNE_INVOICE_TYPE_REFUND = "refund"

RETRIABLE_HTTP = {429, 500, 502, 503, 504}
FUNCTIONAL_HTTP = {400, 401, 403, 404}
